### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by bingbingbog** [huangke19/TikTokSpider#2]
请输入你要爬取的抖音用户id: 6600646945406979341
Traceback (most recent call last):
  File "G:/TikTokSpider-master/dyspider.py", line 135, in <module>
    main()
  File "G:/TikTokSpider-master/dyspider.py", line 122, in main
    username, dytk = get_name_and_dytk(_id)
TypeError: 'NoneType' object is not iterable

Process finished with exit code 1

**Comment by huangke19** [comment]
> 请输入你要爬取的抖音用户id: 6600646945406979341
> Traceback (most recent call last):
> File "G:/TikTokSpider-master/dyspider.py", line 135, in 
> main()
> File "G:/TikTokSpider-master/dyspider.py", line 122, in main
> username, dytk = get_name_and_dytk(_id)
> TypeError: 'NoneType' object is not iterable
> 
> Process finished with exit code 1

看README，是输入抖音id，不是抖音号

**Comment by bingbingbog** [comment]
我输入的确实是id啊
https://www.iesdouyin.com/share/video/6600646945406979341/?region=CN&mid=6600647002776668941&u_code=l0l5gdld&titleType=title&utm_source=copy_link&utm_campaign=client_share&utm_medium=android&app=aweme&iid=44069215514&timestamp=1536906069

**Comment by huangke19** [comment]
> 我输入的确实是id啊
> https://www.iesdouyin.com/share/video/6600646945406979341/?region=CN&mid=6600647002776668941&u_code=l0l5gdld&titleType=title&utm_source=copy_link&utm_campaign=client_share&utm_medium=android&app=aweme&iid=44069215514&timestamp=1536906069



> 我输入的确实是id啊
> https://www.iesdouyin.com/share/video/6600646945406979341/?region=CN&mid=6600647002776668941&u_code=l0l5gdld&titleType=title&utm_source=copy_link&utm_campaign=client_share&utm_medium=android&app=aweme&iid=44069215514&timestamp=1536906069

请输用户id，你这个是单个视频的id，单个视频的下载方法看Notes.md

**Comment by bingbingbog** [comment]
应该是分享名片，然后再打开连接，万分感谢

**Comment by huangke19** [comment]
> 应该是分享名片，然后再打开连接，万分感谢

不客气，如果觉得有用请star一个，哈哈
